# Generated by Django 5.1.1 on 2024-10-08 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 8, 19, 8, 5, 78320, tzinfo=datetime.timezone.utc), verbose_name='Entry Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='location',
            field=models.CharField(default=datetime.datetime(2024, 10, 8, 19, 8, 57, 426151, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
