# Generated by Django 5.1.1 on 2024-10-08 21:06

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_diary_date_diary_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', main_app.models.DynamicChoiceField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='Emotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_check', models.BooleanField()),
                ('community_activities', models.CharField()),
                ('time_spent', models.IntegerField()),
                ('gratitude_list', models.TextField()),
                ('vices', models.TextField(verbose_name='')),
                ('diary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.diary')),
            ],
        ),
        migrations.CreateModel(
            name='Mental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation', models.BooleanField()),
                ('time_spent', models.IntegerField()),
                ('fears', models.TextField(max_length=100)),
                ('desires', models.TextField(max_length=100)),
                ('diary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.diary')),
                ('learning_goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=100)),
                ('lunch', models.CharField(max_length=100)),
                ('dinner', models.CharField(max_length=100)),
                ('snacks', models.CharField(max_length=100)),
                ('exercise', models.BooleanField()),
                ('body_part_worked', models.CharField()),
                ('workout_link', models.TextField(verbose_name='')),
                ('diary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.diary')),
            ],
        ),
    ]
