# Generated by Django 5.1.1 on 2024-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_goals_alter_diary_options_emotional_mental_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='emotional',
            name='drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotional',
            name='morning_mood',
            field=models.CharField(choices=[('H', 'Happy'), ('O', 'Okay'), ('D', 'Down'), ('S', 'Sad')], default='H'),
        ),
        migrations.AddField(
            model_name='emotional',
            name='number_of_drinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physical',
            name='breakfast_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emotional',
            name='community_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emotional',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mental',
            name='meditation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mental',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='physical',
            name='exercise',
            field=models.BooleanField(default=False),
        ),
    ]
