# Generated by Django 5.1.1 on 2024-10-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_diary_images_emotional_drink_emotional_morning_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='images/')),
                ('diary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.diary')),
            ],
        ),
    ]
