# Generated by Django 5.1.1 on 2024-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_diary_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
