# Generated by Django 5.1.1 on 2024-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_emotional_community_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical',
            name='length_of_workout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='physical',
            name='snacks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical',
            name='workout_link',
            field=models.TextField(blank=True, null=True, verbose_name='Type of Workout'),
        ),
    ]
