# Generated by Django 5.1.1 on 2024-10-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_physical_length_of_workout_alter_physical_snacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotional',
            name='evening_mood',
            field=models.CharField(blank=True, choices=[('H', 'Happy'), ('O', 'Okay'), ('D', 'Down'), ('S', 'Sad')], default='H', null=True),
        ),
        migrations.AlterField(
            model_name='mental',
            name='diary_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.diary'),
            preserve_default=False,
        ),
    ]
