# Generated by Django 5.1.1 on 2024-10-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='diary_photos',
            new_name='diary',
        ),
        migrations.AddField(
            model_name='emotional',
            name='emotional_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.goals'),
        ),
        migrations.AddField(
            model_name='physical',
            name='physical_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.goals'),
        ),
    ]
