# Generated by Django 5.1.1 on 2024-10-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_diary_photos_photo_diary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physical',
            name='breakfast_check',
        ),
    ]
